### PR TITLE
BeatHeartDisease Alpha

### PR DESCRIPTION
**Pull request by cswingle98**
Harry Mellsop
Collin Schlager
Colton Swingle

### CODE REVIEW

**Comment by schlagercollin** [comment]
Preliminary PR prior to assignment 4 review

**Comment by schlagercollin** [comment]
FIREBASE RULES

rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
  
  
  	match /providers/{document=**} {
    	allow read;
    }

    match /registered-patients/{email}/{document=**} {
      allow create, update, read, write: if request.auth.token.email == email;
    }
    match /{document=**} {
    	allow create, update, read, write: if exists(/databases/$(database)/documents/providers/$(request.auth.token.email)) && get(/databases/$(database)/documents/providers/$(request.auth.token.email)).data.admin == true;
    }
  }
}

**Comment by cswingle98** [comment]
Assignment 4 Submission:

Firestore Rules:

rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
  
  
  	match /providers/{document=**} {
    	allow read;
    }

    match /registered-patients/{email}/{document=**} {
      allow create, update, read, write: if request.auth.token.email == email;
    }
    match /{document=**} {
    	allow create, update, read, write: if exists(/databases/$(database)/documents/providers/$(request.auth.token.email)) && get(/databases/$(database)/documents/providers/$(request.auth.token.email)).data.admin == true;
    }
  }
}

Features:

1. Use Core Bluetooth APIs or HealthKit to collect information from an external Omron blood-pressure (BP) cuff. Save the collection results in Firestore. Create at least one view to visualize BP progress for your patient over time. You may use CareKit charts or ResearchKit charts.
2. Create a provider app that allows an authenticated user to see patient data. The app can be a web-app (ReactJS sample), or another native iPad app. The app must have a way to: (1) see a list of patients, and (2) per patient see at least two data types. Data types include: surveys, healthkit data, location data, bluetooth collected data, and others. Check in with us to confirm that you will receive full credit for your implementation.
3. Study progress charts for blood pressure.
4. Secure rules.
5. Healthkit Health records.
6. CareKit contact cards.
7. Secure provider authorisation for user sign up.

**Comment by schlagercollin** [comment]
This PR is up-to-date with our latest code for the final presentation

**Pull request closed without merging**
