### PR TITLE
Feature: Data Visualization (CKBuildathon)

### PR DESCRIPTION
**Pull request by mster**
Work in progress

Ref: https://github.com/CardinalKit/CardinalKit/issues/23

### CODE REVIEW

**Comment by mster** [comment]
Will rebase and squash.

Usage coming soon!!

**Comment by tlaskey** [comment]
Hello! 

Our team worked on adding visualizations for patient surveys. 

# Feature List

1. We added a visualization tab to the StudiesUI. 
```swift
// add a visualizations tab to your app!
VisualizationsView(color: self.color)
       .tabItem {
           Image("tab_dashboard").renderingMode(.template)
           Text("Visualize")
            }
```
This tab automatically loads tasks found in firebase, processes them using custom data handlers, and outputs the visualizations in the tab. A user will need to add their task and write a custom processing handler in `processGroupSurveys`. 
## Example
### Using ResearchKit's Towers of Hanoi Task
```swift
static let towerTask: ORKOrderedTask = {
        let intendedUseDescription = "Demo of data."
        
        return ORKOrderedTask.towerOfHanoiTask(withIdentifier: "Hanoi", intendedUseDescription: intendedUseDescription, numberOfDisks: 4, options: ORKPredefinedTaskOption())
    }()
```
### Processing Task
```swift
case "Hanoi":
                print("processing Hanoi task")

                let title = identifier as String
                let description = "Time taken in seconds."
                let type = "DiscreteGraph"
                var values = [[],[]]
                
                // processess && update values
                for surveys in (surveysDict[identifier])! {
                    let results = surveys["results"] as! NSArray
                    let result = results[2] as! NSDictionary
                    let resultOfResults = result["results"] as! NSArray
                    let resultOfResultOfResults = resultOfResults[0] as! NSDictionary
                    let moves = resultOfResultOfResults["moves"] as! NSArray
                    let move = moves[moves.count - 1] as! NSDictionary
                    let ts = move["timestamp"] as! Double
                    
                    values[0].append(ORKValueRange(value: 0))
                    values[1].append(ORKValueRange(value: ts))
                }

                let data = VisualizationData(
                    title: title,
                    description: description,
                    type: type,
                    values: values
                )
                visDataArray.append(data)
```
This will allow for fully customizable visualizations for tasks made by the user. All the user needs to do is add a case in the switch statement with their tasks identifier. E.g. `Hanoi` and they will be given all the survey payloads corresponding to that task identifier. The user decides how they want to process the information and what type of graph to display. 

2. Modified `CKConfiguration.plist` to turn on/off thumbnail visualizations in the `VisualizationView`. 
```swift
// set visualization config
if (config["showThumbnail"]) != nil && (config["showThumbnail"]) == "true" {
     self.showThumbnail = true
}
```

3. Added the option to export a visualization to a pdf inside `VisualizationInspectionView` @khartmansjsu 

## Future Considerations
1. Processing survey data should probably be moved to a separate file. If the user has a sizeable amount of custom surveys, `processGroupedSurveys` will become very large. I would consider moving the processing to a `ProcessSurveyHandler` class, which would contain functions specific to survey identifiers and would handle sending the survey payloads to the correct survey processing function. 
2. Given the time we had and our minimal experience in Swift/iOS dev, I think this is only a rough implementation of what we wanted to get done. Feedback is greatly appreciated on how it can be improved. 

Thank you for hosting the buildathon! It was a ton of fun.

**Comment by mster** [comment]
Had an awesome time contributing. I know we all would love to continue to build out this feature in the near future. We'll circle back soon and help resolve/clean up the code and commits before merging. Whats up right now is very much a Hackathon project. Hopefully I've earned a bit of sleep! 😸 

Thanks again to @varunshenoy @ssgutierrez42 for their expertise and help along the way.

**Comment by khartmansjsu** [comment]
Hello!
Thank you all for hosting the Buildathon and making the CardinalKit source available to us to build out. Our team learned Swift from the ground up while building the above features, and we are grateful for the help that @varunshenoy, @ssgutierrez42, and others gave along the way.
Hopefully the code we've added serves as a checkpoint from which future contributors can start when further developing CardinalKit.

**Pull request closed without merging**
