### PR TITLE
Adds "Sign in with Apple" step

### PR DESCRIPTION
**Pull request by ApolloZhu**
# Usage

1. Follow the [Firebase setup tutorial](https://firebase.google.com/docs/auth/ios/apple) until right before the "Sign in with Apple and authenticate with Firebase" section to setup Firebase and Xcode project.
2. Instantiate a Sign in with Apple step. By default, it uses the "**Sign in with Apple Title**" and "**Sign in with Apple Text**" entry from `CKConfiguration.plist`, and collects user's email address:
```swift
let signInWithAppleStep = CKSignInWithAppleStep(identifier: "SignInWithAppleStep")
```
3. (Optionally,) further customize the step in code. For example, to collect both the name and the email of a user:
```swift
signInWithAppleStep.requestedScopes = [.fullName, .email]
```
4. Add the above step to a task.
5. Configure the task presentation view controller to use the correct view controller for this step:
```swift
func taskViewController(_ taskViewController: ORKTaskViewController,
                        viewControllerFor step: ORKStep) -> ORKStepViewController? {
    // Use the correct view controller for this step.
    if step is CKSignInWithAppleStep {
        return CKSignInWithAppleStepViewController(step: step)
    }
    ...
}
```

### CODE REVIEW

**Comment by varunshenoy** [comment]
Hey @ApolloZhu — this looks great! Any chance a user could toggle between email/password authentication and sign in with Apple via `CKConfiguration.plist` in the onboarding phase of the sample app? That would be a fantastic feature!

**Comment by ApolloZhu** [comment]
Thanks for the suggestion, I'll work on that next. Was also thinking about how to integrate this into the sample app.

**Comment by varunshenoy** [comment]
Best way to incorporate it would be via the `OnboardingVC` class in the `OnboardingUI.swift` file — a simple `if` statement reading from the .plist would a be a perfect way to toggle between Apple and Email/Password auth.

**Comment by varunshenoy** [comment]
@all-contributors please add ApolloZhu for code!

**Pull request merged**
